// Code generated by scripts/generate-contract.py; DO NOT EDIT.
package contract

import (
	"net/url"
	"strconv"
)

// Value retains the original JSON value, including null and malformed values.
// T describes the API contract; callers apply their existing tolerant conversions.
type Value[T any] struct{ Raw any }

type SearchHistoryBody = HistoryPage
type SearchHistoryRequest struct {
	SearchType string
	Value      string
	Limit      int
	Offset     int
}

func (r SearchHistoryRequest) Path(escape func(string) string) string {
	return "/api/v1/history/" + escape(r.SearchType) + "/" + escape(r.Value) + ""
}
func (r SearchHistoryRequest) Query() url.Values {
	return url.Values{
		"limit":  {strconv.Itoa(r.Limit)},
		"offset": {strconv.Itoa(r.Offset)},
	}
}
func (r SearchHistoryRequest) Headers() url.Values {
	return url.Values{}
}

const SearchHistorySearchTypeRequestID = "request_id"
const SearchHistorySearchTypeDeviceID = "device_id"
const SearchHistorySearchTypeUserHID = "user_hid"
const SearchHistorySearchTypeVisitorID = "visitor_id"
const SearchHistorySearchTypeIP = "ip"
const SearchHistorySearchTypeSessionID = "session_id"
const SearchHistorySearchTypeCookieID = "cookie_id"

func SearchHistorySearchTypeValues() []string {
	return []string{"request_id", "device_id", "user_hid", "visitor_id", "ip", "session_id", "cookie_id"}
}

type GetDomainProfileBody = DomainProfile
type GetDomainProfileRequest struct {
	XShieldDomain string
}

func (r GetDomainProfileRequest) Path(escape func(string) string) string { return "/v1/profile" }
func (r GetDomainProfileRequest) Query() url.Values {
	return url.Values{}
}
func (r GetDomainProfileRequest) Headers() url.Values {
	return url.Values{
		"X-Shield-Domain": {r.XShieldDomain},
	}
}

type IdentificationScoredBody = IdentificationScoredEvent
type WebhookPingBody = WebhookPingEvent
type DetectionFlags struct{ raw map[string]any }

func ReadDetectionFlags(raw map[string]any) DetectionFlags { return DetectionFlags{raw: raw} }
func (v DetectionFlags) Abuser() Value[bool]               { return Value[bool]{Raw: v.raw["abuser"]} }
func (v DetectionFlags) AntiDetectBrowser() Value[bool] {
	return Value[bool]{Raw: v.raw["anti_detect_browser"]}
}
func (v DetectionFlags) BrowserAutomation() Value[bool] {
	return Value[bool]{Raw: v.raw["browser_automation"]}
}
func (v DetectionFlags) BrowserVPNProxy() Value[bool] {
	return Value[bool]{Raw: v.raw["browser_vpn_proxy"]}
}
func (v DetectionFlags) CheckIncomplete() Value[bool] {
	return Value[bool]{Raw: v.raw["check_incomplete"]}
}
func (v DetectionFlags) DatacenterIP() Value[bool] { return Value[bool]{Raw: v.raw["datacenter_ip"]} }
func (v DetectionFlags) Incognito() Value[bool]    { return Value[bool]{Raw: v.raw["incognito"]} }
func (v DetectionFlags) IPMismatch() Value[bool]   { return Value[bool]{Raw: v.raw["ip_mismatch"]} }
func (v DetectionFlags) JavascriptDisabled() Value[bool] {
	return Value[bool]{Raw: v.raw["javascript_disabled"]}
}
func (v DetectionFlags) OSMismatch() Value[bool] { return Value[bool]{Raw: v.raw["os_mismatch"]} }
func (v DetectionFlags) OSNotDetected() Value[bool] {
	return Value[bool]{Raw: v.raw["os_not_detected"]}
}
func (v DetectionFlags) PrivacyRelay() Value[bool] { return Value[bool]{Raw: v.raw["privacy_relay"]} }
func (v DetectionFlags) Proxy() Value[bool]        { return Value[bool]{Raw: v.raw["proxy"]} }
func (v DetectionFlags) SearchBot() Value[bool]    { return Value[bool]{Raw: v.raw["search_bot"]} }
func (v DetectionFlags) StunNotChecked() Value[bool] {
	return Value[bool]{Raw: v.raw["stun_not_checked"]}
}
func (v DetectionFlags) SuspiciousPaidClick() Value[bool] {
	return Value[bool]{Raw: v.raw["suspicious_paid_click"]}
}
func (v DetectionFlags) TimezoneMismatch() Value[bool] {
	return Value[bool]{Raw: v.raw["timezone_mismatch"]}
}
func (v DetectionFlags) Tor() Value[bool] { return Value[bool]{Raw: v.raw["tor"]} }
func (v DetectionFlags) VPN() Value[bool] { return Value[bool]{Raw: v.raw["vpn"]} }

const DetectionFlagsFieldCount = 19

type DomainProfile struct{ raw map[string]any }

func ReadDomainProfile(raw map[string]any) DomainProfile { return DomainProfile{raw: raw} }
func (v DomainProfile) Callback() Value[string]          { return Value[string]{Raw: v.raw["Callback"]} }
func (v DomainProfile) CreatedAt() Value[string]         { return Value[string]{Raw: v.raw["CreatedAt"]} }
func (v DomainProfile) Domain() Value[string]            { return Value[string]{Raw: v.raw["Domain"]} }
func (v DomainProfile) PublicKey() Value[string]         { return Value[string]{Raw: v.raw["PublicKey"]} }
func (v DomainProfile) Secret() Value[string]            { return Value[string]{Raw: v.raw["Secret"]} }
func (v DomainProfile) Weight() Value[int64]             { return Value[int64]{Raw: v.raw["Weight"]} }

const DomainProfileFieldCount = 6

type HistoryPage struct{ raw map[string]any }

func ReadHistoryPage(raw map[string]any) HistoryPage { return HistoryPage{raw: raw} }
func (v HistoryPage) Data() Value[[]HistoryRow]      { return Value[[]HistoryRow]{Raw: v.raw["data"]} }
func (v HistoryPage) Total() Value[int64]            { return Value[int64]{Raw: v.raw["total"]} }

const HistoryPageFieldCount = 2

type HistoryRow struct{ raw map[string]any }

func ReadHistoryRow(raw map[string]any) HistoryRow { return HistoryRow{raw: raw} }
func (v HistoryRow) Browser() Value[string]        { return Value[string]{Raw: v.raw["browser"]} }
func (v HistoryRow) CheckIncomplete() Value[bool]  { return Value[bool]{Raw: v.raw["check_incomplete"]} }
func (v HistoryRow) ClickIDType() Value[string]    { return Value[string]{Raw: v.raw["click_id_type"]} }
func (v HistoryRow) ConnectionType() Value[string] {
	return Value[string]{Raw: v.raw["connection_type"]}
}
func (v HistoryRow) CookieID() Value[string]   { return Value[string]{Raw: v.raw["cookie_id"]} }
func (v HistoryRow) Country() Value[string]    { return Value[string]{Raw: v.raw["country"]} }
func (v HistoryRow) CreatedAt() Value[string]  { return Value[string]{Raw: v.raw["created_at"]} }
func (v HistoryRow) DeviceID() Value[string]   { return Value[string]{Raw: v.raw["device_id"]} }
func (v HistoryRow) DeviceType() Value[string] { return Value[string]{Raw: v.raw["device_type"]} }
func (v HistoryRow) Domain() Value[string]     { return Value[string]{Raw: v.raw["domain"]} }
func (v HistoryRow) EntryURL() Value[string]   { return Value[string]{Raw: v.raw["entry_url"]} }
func (v HistoryRow) IP() Value[string]         { return Value[string]{Raw: v.raw["ip"]} }
func (v HistoryRow) IsAbuser() Value[bool]     { return Value[bool]{Raw: v.raw["is_abuser"]} }
func (v HistoryRow) IsAntidetect() Value[bool] { return Value[bool]{Raw: v.raw["is_antidetect"]} }
func (v HistoryRow) IsBrowserAutomation() Value[bool] {
	return Value[bool]{Raw: v.raw["is_browser_automation"]}
}
func (v HistoryRow) IsDatacenter() Value[bool] { return Value[bool]{Raw: v.raw["is_datacenter"]} }
func (v HistoryRow) IsIncognito() Value[bool]  { return Value[bool]{Raw: v.raw["is_incognito"]} }
func (v HistoryRow) IsJsDisabled() Value[bool] { return Value[bool]{Raw: v.raw["is_js_disabled"]} }
func (v HistoryRow) IsOSMismatch() Value[bool] { return Value[bool]{Raw: v.raw["is_os_mismatch"]} }
func (v HistoryRow) IsOSNotDetected() Value[bool] {
	return Value[bool]{Raw: v.raw["is_os_not_detected"]}
}
func (v HistoryRow) IsPrivacyRelay() Value[bool] { return Value[bool]{Raw: v.raw["is_privacy_relay"]} }
func (v HistoryRow) IsProxy() Value[bool]        { return Value[bool]{Raw: v.raw["is_proxy"]} }
func (v HistoryRow) IsSearchBot() Value[bool]    { return Value[bool]{Raw: v.raw["is_search_bot"]} }
func (v HistoryRow) IsStunNotChecked() Value[bool] {
	return Value[bool]{Raw: v.raw["is_stun_not_checked"]}
}
func (v HistoryRow) IsSuspiciousPaidClick() Value[bool] {
	return Value[bool]{Raw: v.raw["is_suspicious_paid_click"]}
}
func (v HistoryRow) IsTimezoneMismatch() Value[bool] {
	return Value[bool]{Raw: v.raw["is_timezone_mismatch"]}
}
func (v HistoryRow) IsTor() Value[bool] { return Value[bool]{Raw: v.raw["is_tor"]} }
func (v HistoryRow) IsVPN() Value[bool] { return Value[bool]{Raw: v.raw["is_vpn"]} }
func (v HistoryRow) OS() Value[string]  { return Value[string]{Raw: v.raw["os"]} }
func (v HistoryRow) ReferrerDomain() Value[string] {
	return Value[string]{Raw: v.raw["referrer_domain"]}
}
func (v HistoryRow) RequestID() Value[string]    { return Value[string]{Raw: v.raw["request_id"]} }
func (v HistoryRow) Score() Value[int64]         { return Value[int64]{Raw: v.raw["score"]} }
func (v HistoryRow) ScoreDetails() Value[string] { return Value[string]{Raw: v.raw["score_details"]} }
func (v HistoryRow) SessionID() Value[string]    { return Value[string]{Raw: v.raw["session_id"]} }
func (v HistoryRow) SiteDomain() Value[string]   { return Value[string]{Raw: v.raw["site_domain"]} }
func (v HistoryRow) TrafficChannel() Value[string] {
	return Value[string]{Raw: v.raw["traffic_channel"]}
}
func (v HistoryRow) TrafficChannelGroup() Value[string] {
	return Value[string]{Raw: v.raw["traffic_channel_group"]}
}
func (v HistoryRow) TrafficReason() Value[string] { return Value[string]{Raw: v.raw["traffic_reason"]} }
func (v HistoryRow) UserHID() Value[string]       { return Value[string]{Raw: v.raw["user_hid"]} }
func (v HistoryRow) UTMCampaign() Value[string]   { return Value[string]{Raw: v.raw["utm_campaign"]} }
func (v HistoryRow) UTMContent() Value[string]    { return Value[string]{Raw: v.raw["utm_content"]} }
func (v HistoryRow) UTMMedium() Value[string]     { return Value[string]{Raw: v.raw["utm_medium"]} }
func (v HistoryRow) UTMSource() Value[string]     { return Value[string]{Raw: v.raw["utm_source"]} }
func (v HistoryRow) UTMTerm() Value[string]       { return Value[string]{Raw: v.raw["utm_term"]} }
func (v HistoryRow) Ver() Value[int64]            { return Value[int64]{Raw: v.raw["ver"]} }
func (v HistoryRow) VisitorID() Value[string]     { return Value[string]{Raw: v.raw["visitor_id"]} }
func (v HistoryRow) WebRtcConnectionType() Value[string] {
	return Value[string]{Raw: v.raw["web_rtc_connection_type"]}
}
func (v HistoryRow) WebRtcCountry() Value[string] {
	return Value[string]{Raw: v.raw["web_rtc_country"]}
}
func (v HistoryRow) WebRtcIP() Value[string] { return Value[string]{Raw: v.raw["web_rtc_ip"]} }
func (v HistoryRow) WebrtcLeakConnectionType() Value[string] {
	return Value[string]{Raw: v.raw["webrtc_leak_connection_type"]}
}
func (v HistoryRow) WebrtcLeakCountry() Value[string] {
	return Value[string]{Raw: v.raw["webrtc_leak_country"]}
}
func (v HistoryRow) WebrtcLeakIP() Value[string] { return Value[string]{Raw: v.raw["webrtc_leak_ip"]} }
func (v HistoryRow) WebrtcLeakSource() Value[string] {
	return Value[string]{Raw: v.raw["webrtc_leak_source"]}
}

const HistoryRowFieldCount = 53

type IdentificationScoredData struct{ raw map[string]any }

func ReadIdentificationScoredData(raw map[string]any) IdentificationScoredData {
	return IdentificationScoredData{raw: raw}
}
func (v IdentificationScoredData) Browser() Value[string] {
	return Value[string]{Raw: v.raw["browser"]}
}
func (v IdentificationScoredData) ConnectionType() Value[string] {
	return Value[string]{Raw: v.raw["connection_type"]}
}
func (v IdentificationScoredData) CookieID() Value[string] {
	return Value[string]{Raw: v.raw["cookie_id"]}
}
func (v IdentificationScoredData) DetectionFlags() Value[DetectionFlags] {
	return Value[DetectionFlags]{Raw: v.raw["detection_flags"]}
}
func (v IdentificationScoredData) DeviceID() Value[string] {
	return Value[string]{Raw: v.raw["device_id"]}
}
func (v IdentificationScoredData) DeviceType() Value[string] {
	return Value[string]{Raw: v.raw["device_type"]}
}
func (v IdentificationScoredData) Domain() Value[string] { return Value[string]{Raw: v.raw["domain"]} }
func (v IdentificationScoredData) LocalIP() Value[IpInfo] {
	return Value[IpInfo]{Raw: v.raw["local_ip"]}
}
func (v IdentificationScoredData) ObservedAt() Value[string] {
	return Value[string]{Raw: v.raw["observed_at"]}
}
func (v IdentificationScoredData) OS() Value[string] { return Value[string]{Raw: v.raw["os"]} }
func (v IdentificationScoredData) PublicIP() Value[IpInfo] {
	return Value[IpInfo]{Raw: v.raw["public_ip"]}
}
func (v IdentificationScoredData) RequestID() Value[string] {
	return Value[string]{Raw: v.raw["request_id"]}
}
func (v IdentificationScoredData) RiskScore() Value[int64] {
	return Value[int64]{Raw: v.raw["risk_score"]}
}
func (v IdentificationScoredData) SessionID() Value[string] {
	return Value[string]{Raw: v.raw["session_id"]}
}
func (v IdentificationScoredData) Signals() Value[[]Signal] {
	return Value[[]Signal]{Raw: v.raw["signals"]}
}
func (v IdentificationScoredData) TrafficSource() Value[TrafficSource] {
	return Value[TrafficSource]{Raw: v.raw["traffic_source"]}
}
func (v IdentificationScoredData) UserHID() Value[string] {
	return Value[string]{Raw: v.raw["user_hid"]}
}
func (v IdentificationScoredData) VisitorID() Value[string] {
	return Value[string]{Raw: v.raw["visitor_id"]}
}

const IdentificationScoredDataFieldCount = 18

type IdentificationScoredEvent struct{ raw map[string]any }

func ReadIdentificationScoredEvent(raw map[string]any) IdentificationScoredEvent {
	return IdentificationScoredEvent{raw: raw}
}
func (v IdentificationScoredEvent) CreatedAt() Value[string] {
	return Value[string]{Raw: v.raw["created_at"]}
}
func (v IdentificationScoredEvent) Data() Value[IdentificationScoredData] {
	return Value[IdentificationScoredData]{Raw: v.raw["data"]}
}
func (v IdentificationScoredEvent) EventType() Value[string] {
	return Value[string]{Raw: v.raw["event_type"]}
}
func (v IdentificationScoredEvent) SchemaVersion() Value[string] {
	return Value[string]{Raw: v.raw["schema_version"]}
}

const IdentificationScoredEventFieldCount = 4

type IpInfo struct{ raw map[string]any }

func ReadIpInfo(raw map[string]any) IpInfo { return IpInfo{raw: raw} }
func (v IpInfo) Country() Value[string]    { return Value[string]{Raw: v.raw["country"]} }
func (v IpInfo) IP() Value[string]         { return Value[string]{Raw: v.raw["ip"]} }

const IpInfoFieldCount = 2

type ScoreDetail struct{ raw map[string]any }

func ReadScoreDetail(raw map[string]any) ScoreDetail { return ScoreDetail{raw: raw} }
func (v ScoreDetail) Description() Value[string]     { return Value[string]{Raw: v.raw["Description"]} }
func (v ScoreDetail) Value() Value[int64]            { return Value[int64]{Raw: v.raw["Value"]} }

const ScoreDetailFieldCount = 2

type Signal struct{ raw map[string]any }

func ReadSignal(raw map[string]any) Signal { return Signal{raw: raw} }
func (v Signal) Name() Value[string]       { return Value[string]{Raw: v.raw["name"]} }
func (v Signal) Weight() Value[int64]      { return Value[int64]{Raw: v.raw["weight"]} }

const SignalFieldCount = 2

type TrafficSource struct{ raw map[string]any }

func ReadTrafficSource(raw map[string]any) TrafficSource { return TrafficSource{raw: raw} }
func (v TrafficSource) Channel() Value[string]           { return Value[string]{Raw: v.raw["channel"]} }
func (v TrafficSource) ClickIDType() Value[string]       { return Value[string]{Raw: v.raw["click_id_type"]} }
func (v TrafficSource) LandingURL() Value[string]        { return Value[string]{Raw: v.raw["landing_url"]} }
func (v TrafficSource) ReferrerDomain() Value[string] {
	return Value[string]{Raw: v.raw["referrer_domain"]}
}
func (v TrafficSource) UTMCampaign() Value[string] { return Value[string]{Raw: v.raw["utm_campaign"]} }
func (v TrafficSource) UTMContent() Value[string]  { return Value[string]{Raw: v.raw["utm_content"]} }
func (v TrafficSource) UTMMedium() Value[string]   { return Value[string]{Raw: v.raw["utm_medium"]} }
func (v TrafficSource) UTMSource() Value[string]   { return Value[string]{Raw: v.raw["utm_source"]} }
func (v TrafficSource) UTMTerm() Value[string]     { return Value[string]{Raw: v.raw["utm_term"]} }

const TrafficSourceFieldCount = 9

type WebhookPingEvent struct{ raw map[string]any }

func ReadWebhookPingEvent(raw map[string]any) WebhookPingEvent { return WebhookPingEvent{raw: raw} }
func (v WebhookPingEvent) CreatedAt() Value[string]            { return Value[string]{Raw: v.raw["created_at"]} }
func (v WebhookPingEvent) EventType() Value[string]            { return Value[string]{Raw: v.raw["event_type"]} }
func (v WebhookPingEvent) SchemaVersion() Value[string] {
	return Value[string]{Raw: v.raw["schema_version"]}
}

const WebhookPingEventFieldCount = 3
