#!/usr/bin/env python3
"""Generate the tolerant, typed views used by the supported client."""
import argparse
import json
from pathlib import Path
import re
import shutil
import subprocess

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "internal/contract/models.gen.go"

# Request inputs currently supplied by the supported client's public methods.
# A new required input needs an explicit caller change, not a zero-valued field
# silently omitted from an existing keyed struct literal. New optional inputs
# are left to the server until the SDK exposes an option for them.
CONSUMED_PARAMETERS = {
    "searchHistory": {"HistorySearchType": "path", "HistoryValue": "path", "HistoryLimit": "query", "HistoryOffset": "query"},
    "getDomainProfile": {"ShieldDomain": "header"},
}


def identifier(name):
    initials = {"id": "ID", "ip": "IP", "os": "OS", "hid": "HID", "url": "URL", "utm": "UTM", "vpn": "VPN"}
    parts = re.findall(r"[A-Z]+(?=[A-Z][a-z]|[^A-Za-z]|$)|[A-Z]?[a-z]+|[0-9]+", name)
    return "".join(initials.get(p.lower(), p[:1].upper() + p[1:]) for p in parts)


def generate(document):
    def resolve(schema):
        if "$ref" not in schema:
            return schema
        if not schema["$ref"].startswith("#/"):
            raise ValueError("Only bundled local references are supported")
        value = document
        for key in schema["$ref"][2:].split("/"):
            value = value[key.replace("~1", "/").replace("~0", "~")]
        return resolve(value)

    models = {}

    def go_type(schema):
        target = resolve(schema)
        kind = target.get("type")
        if isinstance(kind, list):
            kinds = [k for k in kind if k != "null"]
            if len(kinds) != 1:
                raise ValueError("Unsupported union type")
            kind = kinds[0]
        if kind == "object":
            if "$ref" not in schema or not schema["$ref"].startswith("#/components/schemas/"):
                raise ValueError("Object views require a named component")
            name = schema["$ref"].rsplit("/", 1)[1]
            if name not in models:
                models[name] = None
                fields = {key: go_type(value) for key, value in target.get("properties", {}).items()}
                if len({identifier(k) for k in fields}) != len(fields):
                    raise ValueError(f"Go field name collision in {name}")
                models[name] = fields
            return name
        if kind == "array":
            return "[]" + go_type(target["items"])
        return {"string": "string", "integer": "int64", "number": "float64", "boolean": "bool"}[kind]

    lines = [
        "// Code generated by scripts/generate-contract.py; DO NOT EDIT.",
        "package contract", "", 'import ("net/url"; "strconv")', "",
        "// Value retains the original JSON value, including null and malformed values.",
        "// T describes the API contract; callers apply their existing tolerant conversions.",
        "type Value[T any] struct { Raw any }", "",
    ]
    operations = {}
    for section in ("paths", "webhooks"):
        for path, item in document[section].items():
            for method in ("get", "post", "put", "patch", "delete", "head", "options", "trace"):
                op = item.get(method)
                if op and op.get("operationId") in ("searchHistory", "getDomainProfile", "identificationScored", "webhookPing"):
                    if op["operationId"] in CONSUMED_PARAMETERS and method != "get":
                        raise ValueError(f"Unsupported HTTP method for {op['operationId']}: {method.upper()}; expected GET; update the SDK transport caller")
                    operations[op["operationId"]] = (path, item, op)
    for op_id in ("searchHistory", "getDomainProfile", "identificationScored", "webhookPing"):
        path, item, op = operations[op_id]
        name = identifier(op_id)
        body = (resolve(op["responses"]["200"])["content"]["application/json"] if "responses" in op and op_id in ("searchHistory", "getDomainProfile") else resolve(op["requestBody"])["content"]["application/json"])
        lines.append(f"type {name}Body = {go_type(body['schema'])}")
        if op_id not in ("searchHistory", "getDomainProfile"):
            continue
        params = []
        consumed_refs = {f"#/components/parameters/{key}": location for key, location in CONSUMED_PARAMETERS[op_id].items()}
        for source in item.get("parameters", []) + op.get("parameters", []):
            parameter = resolve(source)
            if source.get("$ref") not in consumed_refs:
                if parameter.get("required") or parameter.get("in") == "path":
                    raise ValueError(f"Unsupported required parameter in {op_id}: {parameter['in']} {parameter['name']}; update the SDK caller and consumed parameter mapping")
                continue
            expected_location = consumed_refs[source["$ref"]]
            if parameter.get("in") != expected_location:
                raise ValueError(f"Parameter location changed in {op_id}: {parameter['name']} expected {expected_location}, got {parameter.get('in')}; update the SDK transport caller")
            params.append(parameter)
        fields = [(p, go_type(p["schema"])) for p in params]
        lines.append(f"type {name}Request struct {{")
        for p, typ in fields:
            # Request counts use int, matching the public client's options.
            lines.append(f"{identifier(p['name'])} {('int' if typ == 'int64' else typ)}")
        lines.append("}")
        path_expr = json.dumps(path)
        for p, typ in fields:
            if p["in"] == "path":
                if typ != "string":
                    raise ValueError("Only string path parameters are supported")
                path_expr = path_expr.replace("{" + p["name"] + "}", f'" + escape(r.{identifier(p["name"])}) + "')
        lines.append(f"func (r {name}Request) Path(escape func(string) string) string {{ return {path_expr} }}")
        for location, method in (("query", "Query"), ("header", "Headers")):
            lines.append(f"func (r {name}Request) {method}() url.Values {{ return url.Values{{")
            for p, typ in fields:
                if p["in"] == location:
                    field = f"r.{identifier(p['name'])}"
                    value = {"string": field, "int64": f"strconv.Itoa({field})", "bool": f"strconv.FormatBool({field})"}.get(typ)
                    if value is None:
                        raise ValueError(f"Unsupported parameter type {typ}")
                    lines.append(f"{json.dumps(p['name'])}: {{{value}}},")
            lines.append("} }")
        for p, typ in fields:
            enum = resolve(p["schema"]).get("enum")
            if enum:
                if typ != "string":
                    raise ValueError("Only string request enums are supported")
                prefix = name + identifier(p["name"])
                for value in enum:
                    lines.append(f"const {prefix}{identifier(value)} = {json.dumps(value)}")
                lines.append(f"func {prefix}Values() []string {{ return []string{{" + ",".join(json.dumps(v) for v in enum) + "} }")
    go_type({"$ref": "#/components/schemas/ScoreDetail"})
    for name, fields in sorted(models.items()):
        lines.extend([f"type {name} struct {{ raw map[string]any }}", f"func Read{name}(raw map[string]any) {name} {{ return {name}{{raw: raw}} }}"])
        for key, typ in sorted(fields.items()):
            lines.append(f"func (v {name}) {identifier(key)}() Value[{typ}] {{ return Value[{typ}]{{Raw: v.raw[{json.dumps(key)}]}} }}")
        lines.append(f"const {name}FieldCount = {len(fields)}")
    source = "\n".join(lines).encode() + b"\n"
    command = ["gofmt"] if shutil.which("gofmt") else ["docker", "run", "--rm", "-i", "golang:1.24-bookworm", "gofmt"]
    return subprocess.run(command, input=source, check=True, capture_output=True, timeout=60).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate(yaml.safe_load((ROOT / "resources/shieldlabs-api.yaml").read_text()))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_bytes() != generated:
            raise SystemExit("Generated wire views are stale; run python3 scripts/generate-contract.py")
        print("Generated wire views are current")
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_bytes(generated)


if __name__ == "__main__":
    main()
